# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fed78a6e1e606250eadd46f8ebf9ee9e32c6618f565d8734f0cfed7fc672c1693c2a65e4fe31d232df412b140ebc9a607b1764221a2c68ce28c2677cc4f78392

test:
  secret_key_base: 27e26d12cbbaee154ea01f0eac70f7d8a33e07522d6108f01e182d30bfbb46bf8d0a857f16f2140daf9828c08826a77e323ad0fb0458ba3790d55df6ecf6658f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
